In [9]:
import numpy as np
from scipy import linalg

In [10]:
hilbs = []
dets = []
for i in range(1, 11):
    hilb = linalg.hilbert(i)
    det = np.linalg.det(hilb)
    hilbs.append(hilb)
    dets.append(det)
    

In [11]:
len(hilbs)

10

In [12]:
dets[4]

3.749295132517931e-12

In [13]:
hilbs[4]

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [14]:
hilb_5 = np.copy(hilbs[4])
for i in range(0, (hilb_5.shape[0]-1)):
    elims = np.array([]).reshape(0, 5)
    for j in range(i+1, (hilb_5.shape[0])):
        elim =  hilb_5[j,i] * (hilb_5[i,:] / hilb_5[i,i])
        elims = np.vstack((elims,elim))
    print("rand:", i,elims)
    hilb_5[i+1:, :] = hilb_5[i+1:, :] - elims

rand: 0 [[0.5        0.25       0.16666667 0.125      0.1       ]
 [0.33333333 0.16666667 0.11111111 0.08333333 0.06666667]
 [0.25       0.125      0.08333333 0.0625     0.05      ]
 [0.2        0.1        0.06666667 0.05       0.04      ]]
rand: 1 [[0.         0.08333333 0.08333333 0.075      0.06666667]
 [0.         0.075      0.075      0.0675     0.06      ]
 [0.         0.06666667 0.06666667 0.06       0.05333333]]
rand: 2 [[0.         0.         0.00833333 0.0125     0.01428571]
 [0.         0.         0.00952381 0.01428571 0.01632653]]
rand: 3 [[0.         0.         0.         0.00071429 0.00142857]]


In [15]:
hilb_5

array([[1.00000000e+00, 5.00000000e-01, 3.33333333e-01, 2.50000000e-01,
        2.00000000e-01],
       [0.00000000e+00, 8.33333333e-02, 8.33333333e-02, 7.50000000e-02,
        6.66666667e-02],
       [0.00000000e+00, 0.00000000e+00, 5.55555556e-03, 8.33333333e-03,
        9.52380952e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.57142857e-04,
        7.14285714e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.26757370e-05]])

In [16]:
#typical determinant of rand(n) and randn(n)

In [23]:
rand_matricies = []
rand_dets = []
randn_matricies = []
randn_dets = []
ns = [50, 100, 200, 400]
for n in ns:
    rand_matrix = np.random.rand(n, n)
    randn_matrix = np.random.randn(n, n)
    rand_matricies.append(rand_matrix)
    randn_matricies.append(randn_matrix)
    
    rand_det = np.linalg.det(rand_matrix)
    randn_det = np.linalg.det(randn_matrix)
    rand_dets.append(rand_det)
    randn_dets.append(randn_det)

/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:2093: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


In [24]:
rand_dets

[14952.013880657596,
 2.89844082351138e+24,
 6.023458532182723e+79,
 5.520479451553968e+219]

In [25]:
randn_dets

[5.017265375883179e+31, 4.180971327066432e+76, 1.1241215877881418e+188, inf]