In [1]:
import numpy as np
from scipy.linalg import toeplitz

In [2]:
v = np.array([0,1,0,0,0,1])
toeplitz(v)

array([[0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 0]])

In [3]:
def v(n):
    v = np.zeros(n)
    v[1] = 1
    v[n-1] = 1
    return v

In [4]:
v(5)

array([0., 1., 0., 0., 1.])

In [5]:
toeplitz(v(5))

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [6]:
for i in range(5, 13):
    print(np.linalg.det(toeplitz(v(i))))

2.0
-4.0
2.0
0.0
2.0
-4.0
2.0
0.0


In [49]:
n = 11
for i in range(n):
    first_row = toeplitz(v(n))[0, i]
    print("firt row:", i, first_row)
    cofactor_row = np.linalg.det(toeplitz(v(n))[1:, [j for j in range(n) if j != i]])
    print("row cofactor:", i, cofactor_row)

firt row: 0 0.0
row cofactor: 0 -1.0
firt row: 1 1.0
row cofactor: 1 -1.0
firt row: 2 0.0
row cofactor: 2 1.0
firt row: 3 0.0
row cofactor: 3 1.0
firt row: 4 0.0
row cofactor: 4 -1.0
firt row: 5 0.0
row cofactor: 5 -1.0
firt row: 6 0.0
row cofactor: 6 1.0
firt row: 7 0.0
row cofactor: 7 1.0
firt row: 8 0.0
row cofactor: 8 -1.0
firt row: 9 0.0
row cofactor: 9 -1.0
firt row: 10 1.0
row cofactor: 10 1.0
